name: ocr_corrector
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - pip
  - python==3.10 
  - numpy
  - cython
  - sentencepiece
  - fairseq
  - certifi
  - pip:
    - pillow==11.1.0
    - pandas==2.2.3
    - mcerp==0.12
    - requests==2.32.3
    - unicategories==0.1.2
    - scikit-learn==1.6.0
    - pdf2image==1.17.0
    - xlsxwriter==3.2.0
    - pdfplumber==0.11.5
    - google-cloud-vision==3.10.0
    - python-dotenv==1.0.1
    - unidecode==1.3.8
    - laserembeddings==1.1.2
    - flask==3.1.0
    - opencv-python==4.10.0.84
    - flask-cors==5.0.0
    - openpyxl==3.1.5
    - langdetect==1.0.9
    - deskew==1.5.1